site: Roberto L. Delgado
url: https://rldelgado.com/
title: Roberto L. Delgado
description: Full Stack Web Developer
twitter:
  username: roskideluge
  card: summary
  creator: #yourusername
author:
  twitter: roskideluge
  name: #yourusername
  avatar:
  email: #youremail
  url: #yoururl
# permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    # permalink: /:name
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext
    # permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"